### ISSUE TITLE
Question / issue - Session cookie expiry

### ISSUE THREAD

**Issue by bovas85** [voltace/browser-cookies#19]
I don't seem to be able to tell if a cookie is expired or not.

When I set it on chrome with a session expiry, it shows a 1969 date but I'm still able to retrieve it after session ends.

Is there a way to tell it's expired and needs updating (or overwrite it?)

**Comment by artofrawr** [comment]
This could possibly be caused by having Chrome set to "Continue where you left off". Several browsers break session cookie functionality, in order to keep tabs open and allow their users to continue their browsing sessions even after they had closed the browser.

Further reading: https://stackoverflow.com/questions/10617954/chrome-doesnt-delete-session-cookies
